### ISSUE TITLE
internal URL considered invalid

### ISSUE THREAD

**Issue by fangebault-linagora** [Tanaguru/Tanaguru#121]
It is not possible to specify a URL pointing to a local domain when creating a new contract.
For example: http://mywebapp.test.local/ yields "Please enter a valid URL (ex: http(s)://example.com)".
I figured out that the the domain part of the URL has to end with a IANA-defined top-level domain to be considered valid.

Maybe this restriction is intentional. Then can someone explain why?
Otherwise the fix is quite simple and I can provide a patch for that.

**Comment by jkowalczyk** [comment]
Hello, 
Which version are you using?
There is nothing intentional in this restriction.
The URL is tested regarding the UrlValidator provided by apache commons library. This has been changed recently !!!! Before this, a regexp was used.
[Feel free to fix it](https://github.com/Tanaguru/Tanaguru/wiki/Contribute-to-Tanaguru), but keep in mind that this control can't be completely turn off. 

Regards
