### ISSUE TITLE
How do I add a new language? How do I remove unnecessary languages?

### ISSUE THREAD

**Issue by zwiastunsw** [Tanaguru/Tanaguru#167]
How can I add a new language to Tanaguru, for example Polish. How can I remove unnecessary languages such as Spanish and German?

**Comment by fhalna** [comment]
hello, 
You can use https://crowdin.com/project/tanaguru (sorry we reactivate the project).
it would be interesting to look at rgaa.tanaguru.com to also think about translate all the criteria /  rules (but to wait the 4th version of RGAA that will be compliant with WCAG 2.1 available in september )

**Comment by fhalna** [comment]
i will update crowdin soon, team is on holiday now ;)

**Comment by zwiastunsw** [comment]
Thx for your reply but... I don't expect an answer to the question how to translate to another language, but how to configure it. I would be grateful for the information. Converting language files alone is not a good solution.

**Comment by edaconceicao** [comment]
Hi ,

To add a new language, you must create all properties files with the translation in Polish.
If you want Polish as an added switchable language, the created properties files name must follow this syntax: `example-file-name-I18N_pl.properties`
If you want Polish as default language, you must modify the properties files following this syntax : `example-file-name-I18N.properties` (without language code at the end of the name)

First, you must put and/or modify:
- Files linked to the general navigation in the directory  `web-app/tgol-web-app/src/main/resources/i18n`
- Files linked to referential criterion and rules in the directory  `rules/rgaa3-2017/src/main/resources/i18n` (or any other referential)


Then, you must modify the file `web-app/tgol-web-app/src/main/webapp/WEB-INF/view/template/lang-box.jsp` adding :
 
- this line for each `<c:when>` block of each _X_ language : 
`<c:set var="_X_Url" scope="request" value="?${fn:replace(properQueryString, 'lang=_X_', 'lang=pl')}" />`

- a `<c:when>` block for the new language to add:
```
<c:when test="${fn:contains(pageContext.request.queryString, 'lang=pl')}">
   <c:set var="enUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=pl', 'lang=en')}" />
   <c:set var="frUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=pl', 'lang=fr')}" />
</c:when>
```

- this line for each `<c:otherwise>` block :
`<c:set var="plUrl" scope="request" value="?${properQueryString}&amp;lang=pl"/>`

- This block in the `<ul id="lang-switcher">` block to use the new language : 
```
<li>
   <a href="${plUrl}" title="Switch to polish" lang="pl">
      <abbr title="polish">PL</abbr>
   </a>
</li>
```



To remove a language, you must follow the same process with files concerned by the language. In you case, you must delete files ended by X-I18N **_es** .properties for Spanish and files ended by X-I18N **_de** .properties for German.

In the file `web-app/tgol-web-app/src/main:webapp/WEB-INF/view/template/lang-box.jsp` , you must delete the following lines : 
```
//lines 16 to 24
<c:when test="${fn:contains(pageContext.request.queryString, 'lang=de')}">
   <c:set var="deUrl" scope="request" value="?${properQueryString}"/>
   <c:set var="frUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=de', 'lang=fr')}" />
   <c:set var="esUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=de', 'lang=es')}" />
   <c:set var="enUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=de', 'lang=en')}" />
</c:when>

//lines 29 to 32
<c:set var="esUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=en', 'lang=es')}" />
<c:set var="deUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=en', 'lang=de')}" />

//lines 38 to 41
<c:set var="esUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=fr', 'lang=es')}" />
<c:set var="deUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=fr', 'lang=de')}" />

//lines 43 to 51
<c:when test="${fn:contains(pageContext.request.queryString, 'lang=es')}">
   <c:set var="esUrl" scope="request" value="?${properQueryString}"/>
   <c:set var="enUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=es', 'lang=en')}" />
   <c:set var="frUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=es', 'lang=fr')}" />
   <c:set var="deUrl" scope="request" value="?${fn:replace(properQueryString, 'lang=es', 'lang=de')}" />
</c:when>

//line 53
<c:set var="deUrl" scope="request" value="?${properQueryString}&amp;lang=de"/>
//line 55
<c:set var="esUrl" scope="request" value="?${properQueryString}&amp;lang=es"/>

//line 61
<c:set var="deUrl" scope="request" value="?lang=de"/>
//line 63
<c:set var="esUrl" scope="request" value="?lang=es"/>

//lines 68 to 72
<li>
   <a href="${deUrl}" title="Umsteigen auf Deutsch" lang="de">
      <abbr title="Deutsch">DE</abbr>
   </a>
</li>
//lines 83 to 87
<li>
   <a href="${esUrl}" title="Cambaiar a español" lang="es">
      <abbr title="Español">ES</abbr>
   </a>
</li>
```
Hoping it will help,
Emilie Da Conceicao - Tanaguru Team

**Comment by zwiastunsw** [comment]
Thanks a lot!
